package practica3;

public enum Celda {

    LIBRE, OBSTACULO, PARED, OBJETIVO, RECORRIDO1, RECORRIDO2, RECORRIDO3,
    RECORRIDO4, DESCONOCIDA, ULT_POSICION1, ULT_POSICION2, ULT_POSICION3, ULT_POSICION4;
}
